// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Image image
// swagger:model Image

type Image struct {

	// contenttype
	Contenttype string `json:"contenttype,omitempty"`

	// environment reference
	EnvironmentReference string `json:"environmentReference,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// imagetype
	Imagetype string `json:"imagetype,omitempty"`

	// imported
	Imported bool `json:"imported,omitempty"`

	// origin environment
	OriginEnvironment *Environment `json:"originEnvironment,omitempty"`

	// specifics
	Specifics interface{} `json:"specifics,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// userid
	Userid string `json:"userid,omitempty"`
}

/* polymorph Image contenttype false */

/* polymorph Image environmentReference false */

/* polymorph Image id false */

/* polymorph Image imagetype false */

/* polymorph Image imported false */

/* polymorph Image originEnvironment false */

/* polymorph Image specifics false */

/* polymorph Image title false */

/* polymorph Image userid false */

// Validate validates this image
func (m *Image) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContenttype(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateImagetype(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateOriginEnvironment(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var imageTypeContenttypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disk-raw","disk-qcow2","disk-vmdk","docker-file","docker-image","packerfile"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imageTypeContenttypePropEnum = append(imageTypeContenttypePropEnum, v)
	}
}

const (
	// ImageContenttypeDiskRaw captures enum value "disk-raw"
	ImageContenttypeDiskRaw string = "disk-raw"
	// ImageContenttypeDiskQcow2 captures enum value "disk-qcow2"
	ImageContenttypeDiskQcow2 string = "disk-qcow2"
	// ImageContenttypeDiskVMDK captures enum value "disk-vmdk"
	ImageContenttypeDiskVMDK string = "disk-vmdk"
	// ImageContenttypeDockerFile captures enum value "docker-file"
	ImageContenttypeDockerFile string = "docker-file"
	// ImageContenttypeDockerImage captures enum value "docker-image"
	ImageContenttypeDockerImage string = "docker-image"
	// ImageContenttypePackerfile captures enum value "packerfile"
	ImageContenttypePackerfile string = "packerfile"
)

// prop value enum
func (m *Image) validateContenttypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, imageTypeContenttypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Image) validateContenttype(formats strfmt.Registry) error {

	if swag.IsZero(m.Contenttype) { // not required
		return nil
	}

	// value enum
	if err := m.validateContenttypeEnum("contenttype", "body", m.Contenttype); err != nil {
		return err
	}

	return nil
}

var imageTypeImagetypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["implicit","declarative"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		imageTypeImagetypePropEnum = append(imageTypeImagetypePropEnum, v)
	}
}

const (
	// ImageImagetypeImplicit captures enum value "implicit"
	ImageImagetypeImplicit string = "implicit"
	// ImageImagetypeDeclarative captures enum value "declarative"
	ImageImagetypeDeclarative string = "declarative"
)

// prop value enum
func (m *Image) validateImagetypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, imageTypeImagetypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Image) validateImagetype(formats strfmt.Registry) error {

	if swag.IsZero(m.Imagetype) { // not required
		return nil
	}

	// value enum
	if err := m.validateImagetypeEnum("imagetype", "body", m.Imagetype); err != nil {
		return err
	}

	return nil
}

func (m *Image) validateOriginEnvironment(formats strfmt.Registry) error {

	if swag.IsZero(m.OriginEnvironment) { // not required
		return nil
	}

	if m.OriginEnvironment != nil {

		if err := m.OriginEnvironment.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("originEnvironment")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Image) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Image) UnmarshalBinary(b []byte) error {
	var res Image
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
