// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RuntimeTechnology runtime technology
// swagger:model RuntimeTechnology

type RuntimeTechnology struct {

	// software
	Software string `json:"software,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

/* polymorph RuntimeTechnology software false */

/* polymorph RuntimeTechnology type false */

/* polymorph RuntimeTechnology version false */

// Validate validates this runtime technology
func (m *RuntimeTechnology) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var runtimeTechnologyTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["virtualmachine","container","application"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		runtimeTechnologyTypeTypePropEnum = append(runtimeTechnologyTypeTypePropEnum, v)
	}
}

const (
	// RuntimeTechnologyTypeVirtualmachine captures enum value "virtualmachine"
	RuntimeTechnologyTypeVirtualmachine string = "virtualmachine"
	// RuntimeTechnologyTypeContainer captures enum value "container"
	RuntimeTechnologyTypeContainer string = "container"
	// RuntimeTechnologyTypeApplication captures enum value "application"
	RuntimeTechnologyTypeApplication string = "application"
)

// prop value enum
func (m *RuntimeTechnology) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, runtimeTechnologyTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *RuntimeTechnology) validateType(formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RuntimeTechnology) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RuntimeTechnology) UnmarshalBinary(b []byte) error {
	var res RuntimeTechnology
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
